const SUPPORTED_INDEXES = ['FTSE_100', 'FTSE_250', 'FTSE_350', 'FTSE_ALL_SHARE'];

const SUPPORTED_ATTRIBUTES = {
  REVENUE: 'Revenue',
  PRE_TAX_PROFIT: 'Pre Tax Profit',
  OPERATING_PROFIT: 'Operating Profit',
};

const SUPPORTED_STRATEGIES = {
  FIRST_LAST_COMPARISON: 'First Year vs Last Year',
  LAST_X_YEARS_COMPARISON: 'Increasing for Last X Years',
  FIRST_X_YEARS_COMPARISON: 'Increasing for First X Years',
  ALL_YEARS_COMPARISON: 'Increasing Every Year',
};

export { SUPPORTED_INDEXES, SUPPORTED_ATTRIBUTES, SUPPORTED_STRATEGIES };
